In [1]:
import numpy as np

In [6]:
def get_chess(a):
    chess_board = np.zeros((a, a))
    chess_board[1::2, ::2] = 1
    chess_board[::2, 1::2] = 1
    return chess_board

In [7]:
get_chess(3)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

### Задание 10.7

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

Пример:
``` python
array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)
```

In [9]:
import numpy as np

def shuffle_seed(array):
    seed = np.random.randint(0, 2**32)
    np.random.seed(seed)
    return (np.random.choice(array, len(array), replace=False), seed)

1.21.5


### Задание 10.8

Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

Пример:
``` python
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)
```

In [18]:
import numpy as np
from itertools import combinations

def min_max_dist(*vectors):
    result = None
    combos = combinations(vectors, 2)
    
    for vec_1, vec_2 in combos:
        dist = np.linalg.norm(vec_1 - vec_2)
        if result is None:
            result = [dist, dist]
        elif dist < result[0]:
            result[0] = dist
        elif dist > result[1]:
            result[1] = dist

    return tuple(result)

In [19]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

### Задание 10.9

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

Пример:
```python
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
# True
```

In [ ]:
import numpy as np
from itertools import combinations


def min_max_dist(*vectors):
    result = None
    combos = combinations(vectors, 2)

    for vec_1, vec_2 in combos:
        if np.dot(vec_1, vec_2) == 0:
            return True

    return False