# 6. Модуль NumPy. Массивы

In [1]:
import numpy as np

In [3]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([[12, 45, 78], [34, 56, 13], [12, 98, 76]])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [4]:
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')


dtype('int64')

In [5]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)


array([ 1,  5,  2,  9, 10], dtype=int8)

In [6]:
arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)


array([  1,   5, -48,   9,  10], dtype=int8)

In [7]:
arr[2] = 125.5
arr
# array([  1,   5, 125,   9,  10], dtype=int8)


array([  1,   5, 125,   9,  10], dtype=int8)

In [8]:
arr[2] = '12'
arr
# array([ 1,  5, 12,  9, 10], dtype=int8)


array([ 1,  5, 12,  9, 10], dtype=int8)

In [9]:
arr[2] = 'test'
# ValueError: invalid literal for int() with base 10: 'test'

ValueError: invalid literal for int() with base 10: 'test'

In [10]:
arr = np.float128(arr)
arr
# array([ 1.,  5., 12.,  9., 10.], dtype=float128)

array([ 1.,  5., 12.,  9., 10.], dtype=float128)

In [13]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
# array([12321, -1234,  3435,  -214,   100], dtype=int32)

arr = np.uint8(arr)
arr
# array([ 33,  46, 107,  42, 100], dtype=uint8)

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [15]:
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
nd_arr = np.array([[12, 45, 78], [34, 56, 13], [12, 98, 76]], dtype=np.int16)

In [16]:
arr.ndim
# 1
nd_arr.ndim
# 2

2

In [17]:
arr.size
# 5
nd_arr.size
# 9

9

In [18]:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)


(3, 3)

In [19]:
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

### Задание 6.6
С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? Ответ округлите до двух знаков после точки.

In [21]:
np.linspace(-6, 21, 60, False, True)

(array([-6.  , -5.55, -5.1 , -4.65, -4.2 , -3.75, -3.3 , -2.85, -2.4 ,
        -1.95, -1.5 , -1.05, -0.6 , -0.15,  0.3 ,  0.75,  1.2 ,  1.65,
         2.1 ,  2.55,  3.  ,  3.45,  3.9 ,  4.35,  4.8 ,  5.25,  5.7 ,
         6.15,  6.6 ,  7.05,  7.5 ,  7.95,  8.4 ,  8.85,  9.3 ,  9.75,
        10.2 , 10.65, 11.1 , 11.55, 12.  , 12.45, 12.9 , 13.35, 13.8 ,
        14.25, 14.7 , 15.15, 15.6 , 16.05, 16.5 , 16.95, 17.4 , 17.85,
        18.3 , 18.75, 19.2 , 19.65, 20.1 , 20.55]),
 0.45)