# 7. Модуль NumPy. Действия с массивами

In [1]:
import numpy as np

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr = np.arange(8)
new_arr = arr.reshape((2, 4), order='F')
new_arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [8]:
arr = np.arange(8)
arr.shape =  (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [12]:
arr = np.arange(3)
print(arr)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans)
print(arr_trans.shape)

[0 1 2]
(3,)
[0 1 2]
(3,)


In [13]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [14]:
arr[2]

1.4

In [15]:
arr[2:4]

array([1.4, 1.6])

In [16]:
arr[::-1]

array([2. , 1.8, 1.6, 1.4, 1.2, 1. ])

In [17]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [18]:
nd_array[1][2]

3.0

In [19]:
nd_array[1, 2]

3.0

In [20]:
nd_array[:2, 2]

array([1., 3.])

In [21]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [22]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

### Задание 7.2

Выполните все действия, указанные в комментариях в файле main.py.

Нумерация в заданиях начинается с нуля.

Пожалуйста, не меняйте названия переменных, в которых должны появиться ответы.

In [26]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new[:, -1][::-1]

array([7, 3])

In [28]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
print(arr_new)
arr_new[-1, -1]

[[0 1 2 3]
 [4 5 6 7]]


7

In [29]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [30]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]
