In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 5,  7, 11],
       [11,  8, 11],
       [ 9,  7, 10]])

In [4]:
B

array([[-2,  0, -2],
       [ 0,  1,  3],
       [-2,  3,  0]])

In [5]:
# Поэлементное умножение
A*B

array([[-10,   0, -22],
       [  0,   8,  33],
       [-18,  21,   0]])

In [8]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-32  40  11]
 [-44  41   2]
 [-38  37   3]]


In [9]:
# Матричное умножение
np.dot(A,B)

array([[-32,  40,  11],
       [-44,  41,   2],
       [-38,  37,   3]])

In [10]:
# Матричное умножение
A@B

array([[-32,  40,  11],
       [-44,  41,   2],
       [-38,  37,   3]])

In [11]:
# Порядок умножения AB != BA
B@A

array([[-28, -28, -42],
       [ 38,  29,  41],
       [ 23,  10,  11]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  5  9  9  9]
 [ 6 10  5 10 11]
 [ 5  9 10  8 11]]
B:
 [[ 1  1]
 [ 1  0]
 [-1  0]
 [-2  3]
 [ 3 -1]]


In [13]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[14, 27],
       [24, 25],
       [21, 18]])

In [14]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [15]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [16]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-3 -4 -2  0]
 [-4  3  0 -1]
 [-1 -1  3  2]
 [ 0 -1 -4  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-3 -8  0  0]
 [-4  6  0  1]
 [-1 -2  0 -2]
 [ 0 -2  0  0]]
DA:
 [[-3 -4 -2  0]
 [-8  6  0 -2]
 [ 0  0  0  0]
 [ 0  1  4  0]]


In [17]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [18]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [19]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [21]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [22]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [23]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

### Задание 7.1
1 point possible (graded)

Даны матрица $A$ и вектор $x$

In [30]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5]).T

In [31]:
A @ x

array([26, 30])

### Задание 7.2
1 point possible (graded)

Даны две матрицы:

In [32]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [34]:
B @ A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

### Задание 7.3
1 point possible (graded)

Дана система векторов:

In [35]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Составьте матрицу $A$, расположив векторы $x$, $y$, $z$ в строках.

In [37]:
A = np.array([x, y, z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [38]:
A.T @ A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

### УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

* В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
* В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.


In [40]:
import pandas as pd

In [41]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
    'Окрашивания': [12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка': [15, 25, 30, 14, 25, 17, 25, 31],
    'Уход': [10, 6, 4, 5, 18, 12, 20, 28]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
    'Окрашивания': [1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка': [0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход': [1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра']
)


###  Задание 7.4
1 point possible (graded)

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий:

In [42]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])


Выберите координаты вектора прибыли салона:

* 1.18,1.36,1.05,1.72,2.05,3.35,1.09,2.75
* 9.1,8.6,8.2,9.7,18.6,6.1,10.3,16.6
* 11.3,15.22,11.9,20.6,41.9,21.2,11.49,38.25 верно
* 50.2,74.88,59.1,67.8,166.6,113.8,66.21,157.75

In [75]:
np.diag((com * Price_DF) @ Count_DF.T)


array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

### Задание 7.5
1 point possible (graded)

Найдите вектор прибыли стилистов.

Выберите координаты полученного вектора:
* 1.18,1.36,1.05,1.72,2.05,3.35,1.09,2.75
* 9.1,8.6,8.2,9.7,18.6,6.1,10.3,16.6
* 11.3,15.22,11.9,20.6,41.9,21.2,11.49,38.25
* 50.2,74.88,59.1,67.8,166.6,113.8,66.21,157.75 верно

In [79]:
np.diag(((1 - com) * Price_DF) @ Count_DF.T)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

### Задание 8.1
1/1 point (graded)
Обратная матрица к матрице $A=\left( \begin{array}{cc}
1 & 2 \\ 
2 & 4 \end{array}
\right)$ ...
* имеет размер 2x2
* симметрична
* не существует верно

In [80]:
A = np.matrix('1, 2; 2, 4')
A

matrix([[1, 2],
        [2, 4]])

In [81]:
np.linalg.inv(A)

LinAlgError: Singular matrix

Матрица, обратная к матрице $A$, не существует так как число, стоящее в знаменателе $a_{11}a_{22}-a_{12}a_{21}=1\bullet 4-2\bullet 2=0$, а деление на 0 запрещено.

### Задание 8.2
4 points possible (graded)

Вычислите обратную матрицу к матрице $A=\left( \begin{array}{cc}
1 & 2 \\ 
2 & 5 \end{array}
\right)
$.

Заполните текстовые поля слева направо, сверху вниз:
$A^{-1} =$


In [82]:
A = np.matrix('1, 2; 2, 5')
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

### Задание 8.3
1/1 point (graded)

Обратная матрица к матрице $A=\left( \begin{array}{cc}
1 & 2 \\ 
2 & 5 \end{array}
\right)
$...

Отметьте все подходящие варианты ответов.
* A целочисленная верно
* B симметричная верно
* C не существует

### Задание 8.4
1 point possible (graded)

Какие числа должны стоять на месте знаков вопроса в представленном ниже равенстве?
$\left( \begin{array}{ccc}
2 & 0 & 0 \\ 
0 & 4 & 0 \\ 
0 & 0 & 5 \end{array}
\right)\cdot \left( \begin{array}{ccc}
? & 0 & 0 \\ 
0 & ? & 0 \\ 
0 & 0 & ? \end{array}
\right)=\left( \begin{array}{ccc}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 1 \end{array}
\right)$

* -2, -4, -5
* 1/2, 1/4, 1/5
* 0, 0 , 0
* -1/2, -1/4, -1/5

### Задание 8.6
3 points possible (graded)

Найдите $det(A),\ det(B),\ det(A+B)$, если:

$A=\left( \begin{array}{cc}
1 & 2 \\ 
1 & 1 \end{array}
\right),\ \ B=\left( \begin{array}{cc}
5 & -2 \\ 
-1 & 4 \end{array}
\right)$

При необходимости округлите ответ до целого числа.

In [83]:
A = np.matrix('1, 2; 1, 1')
B = np.matrix('5, -2; -1, 4')

$det(A) =$

In [86]:
np.linalg.det(A)

-1.0

$det(B) =$

In [87]:
np.linalg.det(B)

17.999999999999996

$det(A+B) =$

In [88]:
np.linalg.det(A+B)

29.99999999999999

### Задание 8.8
2 points possible (graded)

Найдите $det(A),\ det(A^{-1})$, если:
$A=\left( \begin{array}{ccc}
2 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 4 \end{array}
\right)$

Первый ответ необходимо округлить до целого числа, второй — до трёх знаков после точки-разделителя.

In [89]:
A = np.matrix('2, 0, 0; 0, 1, 0; 0, 0, 4')
np.linalg.det(A)

7.999999999999998

In [90]:
np.linalg.det(np.linalg.inv(A))

0.12500000000000003

### Задание 9.1
1/1 point (graded)

Сколько решений имеет система уравнений, представленная ниже?

$\left\{ \begin{array}{c}
2x+9y=0 \\ 
2y-2x=0 \end{array}
\right.$

In [91]:
A = np.matrix('2, 9; 2, -2')
np.linalg.det(A)

-22.000000000000004

Верно:
СЛАУ однородная, а значит у неё всегда есть как минимум тривиальное решение или бесконечное множество решений.

Уравнения в данной системе являются линейно независимыми, а значит существует только одно тривиальное решение, когда $x = 0$ и $y = 0$.

Другими способами решить систему нельзя.

### Задание 9.2
1 point possible (graded)

Сколько решений имеет система уравнений, представленная ниже?
$\left\{ \begin{array}{c}
x-3y=0 \\ 
-3x+9y=0 \end{array}
\right.$

* Одно тривиальное решение: $x = 0$ и $y = 0$
* Одно нетривиальное решение: $x \neq 0$ и $y \neq 0$
* Бесконечное множество решений верно

In [92]:
A = np.matrix('1, -3; -3, 9')
np.linalg.det(A)

0.0

In [93]:
np.linalg.det(np.matrix('1, 1; 2, 3'))

1.0

In [ ]:
np.linalg.matrix_rank(np.matrix('1, 0, 3, 5; 0, 4, 5, 5; 0, 0, 0, 0'))

In [94]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [96]:
np.linalg.inv(A)[1, 0]

0.3750000000000005

УСЛОВИЕ ДЛЯ ЗАДАНИЙ 10.2-10.7

Дана система векторов:

In [97]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])


In [101]:
A = np.array([v1, v2, v3, v4]).T
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [102]:
np.linalg.matrix_rank(A)

4

In [105]:
G = (A.T @ A)
G[0, 3]


-35

In [107]:
round(np.linalg.det(G))

3716648

In [109]:
round(np.linalg.inv(G)[2, 0], 3)

-0.026